In [2]:
import numpy as np

# 넘파이 배열의 구조

- 넘파이 모듈의 기본 배열은 ndarray(n-dimension array: 다차원배열)
- <class 'numpy.ndarray'> 타입 

In [2]:
# 리스트를 다차원배열로 변환
li = [1, 2, 3, 4]
li_arr = np.array(li)
# np.array: 다차원 배열 만드는 함수
li_arr

array([1, 2, 3, 4])

In [3]:
np.ndarray(li) # (1,2,3,4) shape 배열

array([[[[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
          1.69120552e-306],
         [1.89146896e-307, 7.56571288e-307, 4.00544531e-307,
          1.11261095e-306],
         [3.56043054e-307, 1.37961641e-306, 2.22518251e-306,
          1.33511969e-306]],

        [[1.69118108e-306, 8.06632139e-308, 1.20160711e-306,
          1.69119330e-306],
         [1.29062229e-306, 1.42417222e-306, 1.33512648e-306,
          7.56596412e-307],
         [9.34601642e-307, 1.78020169e-306, 8.34445562e-308,
          3.91792476e-317]]]])

In [6]:
# 튜플을 다차원배열로 변환
tu = (1,2,3,4)
tu_arr = np.array(tu)
print(tu_arr, type(tu_arr))
print(np.ndarray(tu)) # 매우 작거나 큰 수 

[1 2 3 4] <class 'numpy.ndarray'>
[[[[6.23042070e-307 4.67296746e-307 1.69121096e-306 1.69120552e-306]
   [1.89146896e-307 7.56571288e-307 4.00544531e-307 1.11261095e-306]
   [3.56043054e-307 1.37961641e-306 2.22518251e-306 1.33511969e-306]]

  [[1.69118108e-306 8.06632139e-308 1.20160711e-306 1.69119330e-306]
   [1.29062229e-306 1.42417222e-306 1.33512648e-306 7.56596412e-307]
   [9.34601642e-307 1.78020169e-306 8.34445562e-308 3.91792476e-317]]]]


넘파이 배열도 mutable의 특징을 가짐 (데이터가 유연, 수정가능함)
- 변수를 다른 변수에 복사한 뒤 데이터를 수정하면 모든 변수의 데이터가 수정됨

In [7]:
co_arr = li_arr
id(co_arr), id(li_arr)
# 완벽하게 일치하는 id

(1497661120656, 1497661120656)

In [8]:
co_arr[0] = 100
co_arr

array([100,   2,   3,   4])

In [9]:
li_arr

array([100,   2,   3,   4])

다차원 배열의 값을 복사해서 새로운 배열을 만들면

동일한 값을 가진 새로운 배열이 만들어지기 때문에 서로 다른 데이터가 됨 

In [11]:
new_arr = np.array(li_arr)
id(new_arr), id(li_arr)

(1497661122864, 1497661120656)

In [12]:
new_arr[0] = 99
new_arr

array([99,  2,  3,  4])

In [13]:
li_arr

array([100,   2,   3,   4])

- 파이썬 리스트는 다양한 자료형을 사용할 수 있지만, 넘파이 배열은 같은 자료형만 넣을 수 있음
    - 다차원 배열을 생성할 때 자료형을 지정하지 않으면 내부의 원소를 보고 자동으로 추정해서 만들어짐.

In [14]:
# float 자료형을 지정해서 다차원 배열 만들기
fl_arr = np.array(li, dtype=float)
fl_arr

array([1., 2., 3., 4.])

In [16]:
# 배열의 데이터타입 확인
fl_arr.dtype

dtype('float64')

In [17]:
np.array([1,1.])

array([1., 1.])

In [18]:
# 갑자기 전부 문자열로 바뀜
np.array([1,1., '1'])

array(['1', '1.0', '1'], dtype='<U32')

In [19]:
np.array([1,1., '1', True])

array(['1', '1.0', '1', 'True'], dtype='<U32')

# 2차원 배열이란 

- 2개의 축을 가지는 배열(행,열)
    - 2개의 1차원 배열이 쌓여서 하나의 2차원 배열이 만들어짐.

In [3]:
arr2d = np.array([[1,2,3], [4,5,6]])

# 각 축의 원소의 개수
print(arr2d.shape)

# 축의 개수 (차원 수)
print(arr2d.ndim)

print(arr2d.dtype)

(2, 3)
2
int32


In [21]:
# 다차원 배열을 1차원 배열로 조회
arr2d.flatten() # 평탄화

array([1, 2, 3, 4, 5, 6])

In [8]:
# 평탄화 다른 방법: concatenate
print(np.concatenate(arr2d))
# 평탄화 3: reshape(-1)
print(arr2d.reshape(-1))

[1 2 3 4 5 6]
[1 2 3 4 5 6]


In [22]:
# 1차원 배열에서 원소 조회하기 
li_arr

array([100,   2,   3,   4])

In [23]:
li_arr[0]

100

In [24]:
# 다차원배열에서 원소 조회
list2d = arr2d.tolist() # 배열을 리스트로 변환
list2d

[[1, 2, 3], [4, 5, 6]]

In [25]:
# 리스트는 정수만 이용해서 원소 조회 가능 
# 따라서 리스트 내 리스트의 원소를 조회할 때는 인덱스를 두번 사용해야함.
list2d[0][1]

2

In [26]:
list2d[0,1]

TypeError: list indices must be integers or slices, not tuple

In [40]:
import tensorflow as tf 

a = tf.constant(2)
print(tf.rank(a)) # rank:차원수 (ndim)
print(a.ndim)
print(a)
print(a.numpy())

b = tf.constant([[1,2],[3,4]])
print(tf.rank(b))
print(b.ndim)
print(b)
print(b.numpy())

tf.Tensor(0, shape=(), dtype=int32)
0
tf.Tensor(2, shape=(), dtype=int32)
2
tf.Tensor(2, shape=(), dtype=int32)
2
tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
[[1 2]
 [3 4]]


In [49]:
type(a)

tensorflow.python.framework.ops.EagerTensor

In [42]:
tf.random.uniform([1])

<tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.80790114], dtype=float32)>

In [43]:
tf.random.uniform([1],0,1) # mean, stddev

<tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.23628843], dtype=float32)>

In [44]:
tf.random.normal((3,2),0,1)
# 평균이 0, 표준편차1인 표준정규분포 

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[ 0.61988825,  0.13363943],
       [-1.3503878 , -0.87041277],
       [ 0.02853677,  0.7784559 ]], dtype=float32)>

In [31]:
arr2d[0,1]

2

In [32]:
arr1 = np.array([[0,1,2,3],[4,5,6,7]])
arr1

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [33]:
arr1[1, 2:]

array([6, 7])

In [45]:
# 넘파이 --> tf.Tensor 타입
tf.convert_to_tensor(arr1)

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[0, 1, 2, 3],
       [4, 5, 6, 7]])>

In [46]:
type(tf.convert_to_tensor(arr1))

tensorflow.python.framework.ops.EagerTensor

In [50]:
# 첫번재 행 전체
arr1[0, :]

array([0, 1, 2, 3])

In [54]:
import pandas as pd
import os

os.listdir('../pandas')

df = pd.read_csv('../pandas/scientists.csv')
df.head()

Name        Born        Died    Occupation     born_dt  \
0     Rosaline Franklin  1920-07-25  1958-04-16       Chemist  1920-07-25   
1        William Gosset  1876-06-13  1937-10-16  Statistician  1876-06-13   
2  Florence Nightingale  1820-05-12  1910-08-13         Nurse  1820-05-12   
3           Marie Curie  1867-11-07  1934-07-04       Chemist  1867-11-07   
4         Rachel Carson  1907-05-27  1964-04-14     Biologist  1907-05-27   

      died_dt    age_days  
0  1958-04-16  13779 days  
1  1937-10-16  22404 days  
2  1910-08-13  32964 days  
3  1934-07-04  24345 days  
4  1964-04-14  20777 days

In [55]:
df.iloc[3, :]

Name          Marie Curie
Born           1867-11-07
Died           1934-07-04
Occupation        Chemist
born_dt        1867-11-07
died_dt        1934-07-04
age_days       24345 days
Name: 3, dtype: object

In [56]:
df.iloc[4]

Name          Rachel Carson
Born             1907-05-27
Died             1964-04-14
Occupation        Biologist
born_dt          1907-05-27
died_dt          1964-04-14
age_days         20777 days
Name: 4, dtype: object

In [57]:
df.iloc[-1, 3:]

Occupation    Mathematician
born_dt          1777-04-30
died_dt          1855-02-23
age_days         28422 days
Name: 7, dtype: object

In [58]:
# 두 번째 행의 두 번째 열부터 끝까지
arr1[1, 1:]

array([5, 6, 7])

In [59]:
# 각 행의 두번재 열까지만 
arr1[:, :2]

array([[0, 1],
       [4, 5]])

# 파이썬 리스트와 넘파이 배열의 차이 

- 넘파이: 수학 계산을 위한 라이브러리 
- 넘파이 배열은 배열끼리 연산이 가능하지만, 파이썬 리스트는 값의 추가만 가능 
- 넘파이 배열은 숫자와의 연산도 가능하지만, 파이썬 리스트는 불가능함. 


- 사용 용도
    - 파이썬 리스트는 값을 추가하거나 제거하는 일(데이터 관리)에 사용 
    - 넘파이 배열은 수치 계산이 많고 복잡하거나 다차원배열이 필요할 때 사용

# 연습문제 

1. 아래의 행렬에서 값 7 인덱싱 
2. 아래의 행렬에서 값 14 인덱싱
3. " 배열 [6,7] 슬라이싱
4. " 배열 [7, 12] 슬라이싱 
5. " 배열 [[3,4], [8,9]] 슬라이싱 

In [5]:
m = np.array([[0,1,2,3,4],
             [5,6,7,8,9],
             [10,11,12,13,14]])

print(m[1][2])
print(m[-1][-1])
print(m[1,1:3])
# print(m[1][1], m[2][2])
print(m[1:,2])
print(m[:2,3:])

7
14
[6 7]
[ 7 12]
[[3 4]
 [8 9]]


# 전치 연산 (transpose)

- 2차원 배열의 행과 열을 바꾸는 연산

In [72]:
arr = np.array([[1,2,3], [4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [73]:
arr.shape

(2, 3)

In [74]:
arr.T # = arr.transpose() 

array([[1, 4],
       [2, 5],
       [3, 6]])

In [75]:
arr.transpose

<function ndarray.transpose>

In [76]:
arr.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [77]:
arr.T.shape

(3, 2)

In [78]:
arr.T.T # 원상복귀

array([[1, 2, 3],
       [4, 5, 6]])

# 배열 크기 변형


In [79]:
# np.arange() 중요!
arr1 = np.arange(12)
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [80]:
# arr.reshape(): 형태변형
arr2 = arr1.reshape(3,4)
arr2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [81]:
arr2.shape

(3, 4)

In [82]:
arr1.reshape((3,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [83]:
arr1.reshape([3,4])

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [84]:
# 사용하는 원소의 수가 정해져 있기 때문에 
# reshape의 형태 원소 중 하나는 -1로 대체가능
arr1.reshape(-1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [85]:
arr1.reshape(-1,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [86]:
arr1.reshape(3,-1)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [88]:
arr1.reshape(2,2,-1) # (2,2,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

# 넘파이 함수의 특징 

- 벡터화 연산 
    - 벡터와 행렬의 연산은 구성하는 원소별로 처리하는 것이 보통
    - 동일한 인덱스의 원소끼리 계산을 처리하는 것을 "벡터화 연산"이라고 함. 
    
- 유니버셜 함수 (universal function)
    - 벡터화 연산을 지원하는 특별한 함수 (add, ...)
    - 넘파이 모듈에는 유니버셜 함수도 있고 일반 함수도 있음 (sort...)

In [89]:
# 일반 파이썬 함수의 타입 확인
def test():
    pass

type(test)

function

In [90]:
# 유니버셜 함수 확인
type(np.add)

numpy.ufunc

In [91]:
type(np.sort)
# 유니버셜 함수 아닌 함수도 존재

function

In [92]:
list2d + list2d

[[1, 2, 3], [4, 5, 6], [1, 2, 3], [4, 5, 6]]

In [93]:
np.add(list2d, list2d)
# 똑같은 인덱스 애들끼리 연산

array([[ 2,  4,  6],
       [ 8, 10, 12]])

## 벡터화 연산 

- 벡터화 연산이 필요한 이유 
    - 배열에 대한 수치 연산이 필요하니까 
    - data 리스트 내의 각 값에 2를 곱해야 한다면? 

In [9]:
# 리스트를 통한 풀이
data = list(range(10))
data

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [10]:
[i*2 for i in data]

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [14]:
# 넘파이를 통한 풀이
data = np.array(data)
data * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [15]:
data.tolist()
# [리스트].toarray() 는 존재하지 않음

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

톱니바퀴형 리스트(각 원소마다 개수가 다른 경우) 
- 넘파이 다차원 배열로 만들어줄 수 없음 ! 
    - 리스트로의 변환은 웬만하면 다 됨!! 

### 넘파이 벡터화 연산 

- 벡터화 연산은 비교 연산과 논리 연산을 포함한 모든 종류의 수학 연산에 대해 적용됨.

In [16]:
a = np.array([1,2,3])
b = np.array([10,20,30])

In [17]:
2*a + b

array([12, 24, 36])

In [18]:
a == 2

array([False,  True, False])

In [19]:
b > 10

array([False,  True,  True])

In [20]:
(a==2) & (b>10)

array([False,  True, False])

In [21]:
a[a==2] # 필터링

array([2])

 ### - 배열끼리의 연산 

In [22]:
arr1 = np.arange(6, 10)
arr1

array([6, 7, 8, 9])

In [23]:
arr2 = np.arange(10, 14)
arr2

array([10, 11, 12, 13])

In [24]:
# 두 개의 다차원 배열을 곱하면 
# 동일한 인덱스의 원소끼리 곱셈한 결과인 1차원 배열 반환
arr1 * arr2

array([ 60,  77,  96, 117])

In [25]:
# arr1 에 차원 추가 (수직축 추가)
new_arr1 = arr1[:, np.newaxis]
new_arr1 # (4,1)

array([[6],
       [7],
       [8],
       [9]])

In [26]:
arr1[np.newaxis, :] # (1,4)

array([[6, 7, 8, 9]])

In [27]:
# arr2에도 차원 추가 (수평축 추가)
new_arr2 = arr2[np.newaxis, :]
new_arr2

array([[10, 11, 12, 13]])

In [28]:
new_arr1 * new_arr2
# (4,1) * (1,4) = (4,4)

array([[ 60,  66,  72,  78],
       [ 70,  77,  84,  91],
       [ 80,  88,  96, 104],
       [ 90,  99, 108, 117]])

## 브로드캐스팅 (broadcasting)

- 배열끼리 연산을 하기 위해서는 두 배열의 크기가 같아야함.
- 서로 다른 크기를 가진 배열의 사칙 연산을 하는 경우, 넘파이에서는 크기가 작은 배열을 자동으로 반복 확장하여 크기가 큰 배열에 맞춤.

In [29]:
new_arr1

array([[6],
       [7],
       [8],
       [9]])

In [30]:
new_arr2

array([[10, 11, 12, 13]])

In [31]:
new_arr1 + new_arr2

array([[16, 17, 18, 19],
       [17, 18, 19, 20],
       [18, 19, 20, 21],
       [19, 20, 21, 22]])

In [32]:
# 자동확장된 new_arr1은 다음배열과 같음
new_arr3 = np.array([[i]*4 for i in range(6,10)])
new_arr3

array([[6, 6, 6, 6],
       [7, 7, 7, 7],
       [8, 8, 8, 8],
       [9, 9, 9, 9]])

In [34]:
new_arr3 + new_arr2

array([[16, 17, 18, 19],
       [17, 18, 19, 20],
       [18, 19, 20, 21],
       [19, 20, 21, 22]])

# 연습문제

1. 아래의 배열에서 3의 배수를 찾기
2. 아래의 배열에서 4로 나누면 1이 남는 수 찾기
3. 아래의 배열에서 3으로 나누면 나눠지고 4로 나누면 1이 남는 수 찾기

In [35]:
x = np.array([i for i in range(1,21)])

print(x[x%3==0])
print(x[x%4==1])
print(x[(x%3==0) & (x%4==1)])

[ 3  6  9 12 15 18]
[ 1  5  9 13 17]
[9]


# 축에 따른 연산 

- axis 설정(실행방향) = 판다스 
- 동일한 축에 있는 원소들을 계산하기 위해 필요

In [36]:
# 1차원 배열
arr1 = np.array([1,2,3,4])
arr1

array([1, 2, 3, 4])

In [37]:
# 합계
print(np.sum(arr1))
print(arr1.sum())

10
10


In [39]:
# 최대값 
print(arr1.max())
print(np.max(arr1))

4
4


In [40]:
# 최소값
print(arr1.min())
print(np.min(arr1))

1
1


In [41]:
# 최소값의 위치
print(arr1.argmin())
print(np.argmin(arr1))

0
0


In [42]:
# 최대값의 위치 
print(arr1.argmax())
print(np.argmax(arr1))

3
3


In [43]:
# 퍙균
print(arr1.mean())
print(np.mean(arr1))

# 중앙값
print(np.median(arr1))
# arr1.median() 없음

2.5
2.5
2.5


In [45]:
# 2차원 배열 
arr2 = arr1.reshape(2,2)
print(arr2,'\n')

# 모든 원소 더하기
print(np.sum(arr2))
# 수직 방향으로 같은 열에 속한 원소만 합산 
print(np.sum(arr2, axis=0))
# 수평 방향으로 같은 행에 속한 원소만 합산
print(np.sum(arr2, axis=1))

[[1 2]
 [3 4]] 

10
[4 6]
[3 7]


In [49]:
x = np.random.randint(1,10,(2,3))
print(x, '\n')
print(np.sum(x, axis=0))
print(np.sum(x, axis=1))

[[4 9 8]
 [2 9 8]] 

[ 6 18 16]
[21 19]


In [52]:
# 3차원 배열

arr3 = np.arange(1,9)
print(arr3,'\n')

arr4 = arr3.reshape(2,2,2)
print(arr4,'\n')

# 모든 원소를 더한 합
print(np.sum(arr4))
# 두 행렬의 동일한 인덱스의 원소 합한 값
print(np.sum(arr4, axis=0)) # (2,2)
# 각 2차원 배열의 0번축의 합
print(np.sum(arr4, axis=1))
# 각 2차원 배열의 1번축의 합 
print(np.sum(arr4, axis=2))

[1 2 3 4 5 6 7 8] 

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]] 

36
[[ 6  8]
 [10 12]]
[[ 4  6]
 [12 14]]
[[ 3  7]
 [11 15]]


In [54]:
x = np.random.randint(1,10,(2,3,4))
print(x,'\n')

print(np.sum(x,axis=0))
print(np.sum(x,axis=1))
print(np.sum(x,axis=2))

[[[7 3 7 5]
  [6 8 1 7]
  [2 1 8 7]]

 [[1 1 4 4]
  [6 9 4 6]
  [2 3 4 5]]] 

[[ 8  4 11  9]
 [12 17  5 13]
 [ 4  4 12 12]]
[[15 12 16 19]
 [ 9 13 12 15]]
[[22 22 18]
 [10 25 14]]


# 연습문제

- 실수로 이뤄진 5x6 형태의 데이터 행렬을 만들고 다음의 값 구하기 

1. 전체의 최대값
2. 각 행의 합
3. 각 행의 최대값
4. 각 열의 평균
5. 각 열의 최소값

- \*"각 행의~": axis=1
- \*"각 열의~": axis=0

In [58]:
# 0~1 사이의 랜덤 실수 생성
a = np.random.random((5,6))
print(a, '\n')

# 1
print(np.sum(a))
# 2
print(np.sum(a,axis=1))
# 3
print(np.max(a,axis=1))
# 4
print(np.mean(a,axis=0))
# 5
print(np.min(a,axis=0))

[[0.42290899 0.35450107 0.82153998 0.12610817 0.04224279 0.09818703]
 [0.83936544 0.54687529 0.74273602 0.83639885 0.0827963  0.84070415]
 [0.25488368 0.64815238 0.66111228 0.38112083 0.85276565 0.89084562]
 [0.30073133 0.69270506 0.66612312 0.89448279 0.60685874 0.77416183]
 [0.6637257  0.48486403 0.64800925 0.35440436 0.61719298 0.73694677]] 

16.883450483890293
[1.86548804 3.88887605 3.68888044 3.93506287 3.50514309]
[0.82153998 0.84070415 0.89084562 0.89448279 0.73694677]
[0.49632303 0.54541957 0.70790413 0.518503   0.44037129 0.66816908]
[0.25488368 0.35450107 0.64800925 0.12610817 0.04224279 0.09818703]


# 넘파이 배열 초기화 방법 총정리

In [57]:
# 1. zeros
a = np.zeros((2,3))
print(a)
print()

# 2. ones
b = np.ones((2,1))
print(b)
print()

# 3. empty
# 원소값 초기화하지 않은 배열
# 원소에는 매우크거나 작은값이 들어감
print("np.empty((2,2)) 행렬")
c = np.empty((2,2))
print(c)
print()

# 4. arange
d = np.arange(10,30,5)
print(d)
print()

# 5. full
# 똑같은 값4 가진 행렬
print("np.full((2,2),4) 행렬")
e = np.full((2,2),4)
print(e)
print()

# 6. eye
print("np.eye(3) 행렬")
f = np.eye(3) # 3*3 단위행렬
print(f)
print()
# 단위행렬: 대각선이 1이고 나머지가 0

# 7. randint
g = np.random.randint(3,10,(2,4))
print(g)
print()


# 8. 균등분포 
# 임의값 가진 배열

# 8-1: 0~1 사이의 실수
h = np.random.random((2,2))
print(h)
# 8-2
i = np.random.rand(3,3)
print(i)
# 8-3
j = np.random.uniform((3,3))
print(j)
print()


# 9. 정규분포 (가우시안)
print(np.random.normal(0,1,(2,2))) # 표준정규분포
print(np.random.normal(3.0,2.0,(2,3)))
print()

# 10. 표준정규분포
print(np.random.randn(2,3))
print(np.random.standard_normal((2,3)))

[[0. 0. 0.]
 [0. 0. 0.]]

[[1.]
 [1.]]

np.empty((2,2)) 행렬
[[ 0.33241789 -0.07568418]
 [ 0.2022933  -1.47059635]]

[10 15 20 25]

np.full((2,2),4) 행렬
[[4 4]
 [4 4]]

np.eye(3) 행렬
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

[[4 8 5 9]
 [7 5 6 5]]

[[0.21146465 0.4683142 ]
 [0.51782057 0.99589335]]
[[0.78844189 0.10481514 0.98550697]
 [0.51647066 0.27865943 0.98190688]
 [0.45045756 0.70603776 0.11326815]]
[2.37179063 1.83513611]

[[ 0.07983184  2.5379435 ]
 [ 0.14828899 -0.82678547]]
[[1.12305248 3.07574225 1.14872011]
 [2.61894508 2.14025878 1.28092369]]

[[-0.09527573 -0.36177873 -1.35215975]
 [-0.43994635  0.10938455 -1.17577847]]
[[ 0.73055658  0.24778738 -0.01581224]
 [ 1.25323644  0.42247274 -0.751434  ]]


# Inf와 nan

- 넘파이에서는 무한대를 표현하기 위한 np.inf와 정의할 수 없는 숫자를 나타내는 np.nan이 있음

In [59]:
# 넘파이에서는 zero division 등도 오류 안나고 
# -inf, inf ,nan으로 표현됨
np.array([0,1,-1,0]) / np.array([1,0,0,0])

C:\Users\answl\anaconda3\envs\nlp\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.
C:\Users\answl\anaconda3\envs\nlp\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([  0.,  inf, -inf,  nan])

In [60]:
# 그냥 파이썬 으로는 계산 불가 오류
0 / 0

ZeroDivisionError: division by zero

In [61]:
np.nan == np.nan

False

In [62]:
np.inf == np.inf

True